import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#37393d",
        "on-primary": "#ffffff",
        "on-error-container": "#ffdad6",
        "background": "#0c0e11",
        "error-container": "#93000a",
        "on-secondary-container": "#dce5dd",
        "primary-fixed-dim": "#a7d3a7",
        "surface-container": "#1a1c1f",
        "on-primary-fixed": "#002106",
        "surface-tint": "#8bd691",
        "surface-container-low": "#111316",
        "secondary-fixed": "#dce5dd",
        "on-tertiary-container": "#d0e4ff",
        "inverse-on-surface": "#0c0e11",
        "on-secondary-fixed": "#161d18",
        "surface": "#111316",
        "on-surface": "#e2e2e6",
        "on-surface-variant": "#c4c7cc",
        "inverse-primary": "#2d6b38",
        "surface-container-lowest": "#07080a",
        "surface-dim": "#0c0e11",
        "tertiary": "#aac7ff",
        "on-background": "#e2e2e6",
        "secondary-container": "#3f4940",
        "on-primary-container": "#bdf6bd",
        "tertiary-fixed-dim": "#aac7ff",
        "surface-container-high": "#24262a",
        "primary": "#8bd691",
        "on-tertiary-fixed": "#001b3d",
        "tertiary-container": "#284777",
        "primary-container": "#2d6b38",
        "error": "#ffb4ab",
        "secondary": "#bfc9be",
        "on-primary-fixed-variant": "#145223",
        "surface-variant": "#44474d",
        "on-tertiary-fixed-variant": "#10458e",
        "primary-fixed": "#bdf6bd",
        "on-secondary-fixed-variant": "#3f4940",
        "inverse-surface": "#e2e2e6",
        "outline": "#8e9196",
        "surface-bright": "#37393d",
        "on-secondary": "#29322b",
        "outline-variant": "#44474d"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0px"
      },
      spacing: {
        "sm": "8px",
        "xs": "4px",
        "gutter": "24px",
        "margin-mobile": "16px",
        "margin-desktop": "48px",
        "base": "4px",
        "lg": "24px",
        "md": "16px",
        "xl": "32px"
      },
      fontFamily: {
        "headline-lg-mobile": ["var(--font-manrope)"],
        "body-lg": ["var(--font-inter)"],
        "headline-xl": ["var(--font-manrope)"],
        "body-md": ["var(--font-inter)"],
        "label-sm": ["var(--font-inter)"],
        "headline-lg": ["var(--font-manrope)"],
        "label-md": ["var(--font-inter)"],
        "body-sm": ["var(--font-inter)"],
        "headline-md": ["var(--font-manrope)"]
      },
      fontSize: {
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "14px", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "700" }]
      }
    },
  },
  plugins: [],
};
export default config;
